[package]
name = "glfw_text_rendering"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
cgmath = "0.18.0"
gl = "0.14.0"
glfw = "0.56.0"
glm = "0.2.3"
image = "0.25.1"
rusttype = "0.9.3"
serde = { version = "1.0.198", features = ["derive"] }
